microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/PagosClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/PagoController.java

PR donde se aplica un parche para actualizar los cambios que realizó el servicio externo de pagos en sus endpoints así como las 2 nuevas agregadas por ellos.
**Nuevos**
1. /pagos/metodos/obtener
2. /pagos/metodos/obtener/{idMetodo}
**Modificados**
1. /pagos/bancos/obtener/{id}
2. /pagos/bancos/eliminar/{id}

Parche - endpoints

---

 openapi.yml

PR donde se implementa el estandar de [OpenAPI](https://swagger.io/specification/#definitions) con la versión 3.1.1

Add OpenAPI

---

assets/mockoon/admin.json
microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/AdminClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/AdminController.java

PR donde actualiza los endpoints del servicio externo administrativo con los últimos cambios aplicados...

Acualización microservice-connector

---

 openapi.yml

PR donde se actualiza la documentación de los endpoints, así como agregar las 2 rutas nuevas utilizadas por este servicios (OpenAPI)

Actualización OpenAPI

---

 openapi.yml

Aqui se documentan todos los endpoints (en fichero openapi.yml) de la db y se colocan todos los esquemas de loas colecciones.

Endpoints DB

---

 openapi.yml

add '/broker/POST/autenticacion'

Update  openapi.yml

---

assets/mockoon/admin.json
core/src/main/java/gt/edu/umes/broker/core/endpoints/MCSVAdmin.java
core/src/main/java/gt/edu/umes/broker/core/endpoints/MCSVBroker.java
microservice-config/src/main/resources/configurations/msvc-connector.yml
microservice-connector/pom.xml
microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/AdminClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/config/FeignConfiguration.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/AdminController.java
microservice-validation/src/main/java/gt/edu/umes/broker/validation/client/ClientLogs.java

PR donde se actualiza los endpoints de administración, así como el soporte de redirecciionamientos con **PATCH**

Actulizaciónde endpoints (admin)

---

assets/mockoon/tienda.json
core/src/main/java/gt/edu/umes/broker/core/endpoints/MCSVTienda.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/TiendaClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/TiendaController.java

PR donde se mapea los endpoints del servicio externo (tienda)

Mapeo de endpoints - tienda

---

microservice-identity/src/main/java/gt/edu/umes/broker/identity/controller/AuthController.java
microservice-identity/src/main/java/gt/edu/umes/broker/identity/service/LogsService.java

PR donde se corrige un error lógico cuando se genera un token y se guarda un usuario no existente en la BD...

Arregla un bug con el resgitro de usuarios

---

microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/AdminClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/GasClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/PagosClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/PinturaClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/RepuestosClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/AdminController.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/GasController.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/PagoController.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/PinturaController.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/RepuestosController.java

Este PR mejora la entrada de datos mediante las rutas, es decir. Ahora se permite o se acepta cualquier tipo de datos entrante de los Id's para cualquier tipo de gestor de base de datos, esto con el fin de tener una mayor flexibilidad para gestionar los identificadores usados por los revicios externo.

Mejora en el mapeo

---

README.md
assets/docs/ARRANQUE.md

PR que actualiza la documentación con los últimos cambios dados...

Documentación

---

microservice-validation/src/main/java/gt/edu/umes/broker/validation/controller/ValidationController.java
microservice-validation/src/main/java/gt/edu/umes/broker/validation/service/LogService.java
microservice-validation/src/main/java/gt/edu/umes/broker/validation/service/ValidationService.java

PR donde se cambia el lugar de envio de las señanles de sokets...

Mejora en la detección de logs (Hardware)

---

assets/mockoon/admin.json
core/src/main/java/gt/edu/umes/broker/core/endpoints/MCSVAdmin.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/AdminClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/AdminController.java

PR donde se implementa los nuevos 2 endpoits notificados...

Endpoints administración

---

core/src/main/java/gt/edu/umes/broker/core/endpoints/MCSVRepuestos.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/RepuestosClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/RepuestosController.java

Implementacion de las rutas del proyecto 'Taller y repuestos'

Endpoints Taller y repuestos

---

core/src/main/java/gt/edu/umes/broker/core/Microservice.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/config/GlobalExceptionHandler.java
microservice-validation/src/main/java/gt/edu/umes/broker/validation/controller/ValidationController.java
microservice-validation/src/main/java/gt/edu/umes/broker/validation/service/ConnectorService.java

PR donde se implementa un parche al conectarse con los servicios externos.

Parche de conexiones

---

core/src/main/java/gt/edu/umes/broker/core/endpoints/MCSVTienda.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/TiendaClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/TiendaController.java

PR donde se mapea los enpoints del ervicio de tienda

Mapeo Tienda

---

microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/TiendaClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/TiendaController.java

PR donde se arregla los valores por páremtro en el conector.

Arregla los valores por parametro

---

core/src/main/java/gt/edu/umes/broker/core/endpoints/MCSVAdmin.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/AdminClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/AdminController.java

PR donde se implementa el nuevo endpoint de administración.

Nuevo enpoint ADMIN

---

core/src/main/java/gt/edu/umes/broker/core/endpoints/MCSVAdmin.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/AdminClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/AdminController.java

PR donde se agrega un endpoint faltante...

Add ruras admin

---

microservice-connector/src/main/java/gt/edu/umes/broker/connector/config/GlobalExceptionHandler.java
microservice-gateway/src/main/java/gt/edu/umes/broker/gateway/config/GlobalExceptionHandler.java
microservice-gateway/src/main/java/gt/edu/umes/broker/gateway/filter/AuthenticationFilter.java
microservice-gateway/src/main/java/gt/edu/umes/broker/gateway/util/JwtUtil.java
microservice-gateway/src/main/java/gt/edu/umes/broker/gateway/util/TokenException.java

PR don se corrige las salidas de errores de las diferentes excepciones dadas

Fix. SALIDAS de errores

---

core/src/main/java/gt/edu/umes/broker/core/endpoints/MCSVBroker.java
core/src/main/java/gt/edu/umes/broker/core/model/JsonObjectX.java
microservice-identity/src/main/java/gt/edu/umes/broker/identity/client/ClientLogs.java
microservice-identity/src/main/java/gt/edu/umes/broker/identity/service/AuthService.java
microservice-identity/src/main/java/gt/edu/umes/broker/identity/service/LogsService.java
microservice-logs/src/main/java/gt/edu/umes/broker/logs/controllers/TokenController.java
microservice-logs/src/main/java/gt/edu/umes/broker/logs/models/Token.java
microservice-logs/src/main/java/gt/edu/umes/broker/logs/repository/TokenRepository.java
microservice-logs/src/main/java/gt/edu/umes/broker/logs/services/TokenService.java

PR donde se limina las sesiones de los empleados en la tienda así como ene el taller de vhiculos (matenimiento)

Limitaciones de sesiones

---

core/src/main/java/gt/edu/umes/broker/core/endpoints/MCSVAdmin.java
core/src/main/java/gt/edu/umes/broker/core/endpoints/MCSVPintura.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/AdminClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/client/PinturaClient.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/AdminController.java
microservice-connector/src/main/java/gt/edu/umes/broker/connector/controller/PinturaController.java

PR donde se corrige algunas fallas en el enrutamiento

Fix: Arreglo de enpoints
